//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcursos
    {
        public tblcursos()
        {
            this.tblmatriculas = new HashSet<tblmatriculas>();
        }
    
        public int Id { get; set; }
        public string Nivel { get; set; }
    
        public virtual ICollection<tblmatriculas> tblmatriculas { get; set; }
    }
}
