//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmatriculas
    {
        public int Id { get; set; }
        public Nullable<int> Idcurso { get; set; }
        public Nullable<int> Idest { get; set; }
        public string Nota { get; set; }
    
        public virtual tblcursos tblcursos { get; set; }
        public virtual tblestudiantes tblestudiantes { get; set; }
    }
}
